name: badassdemocrats.com
favicon: null
layout_spectrum: 0.98434
typography_spectrum: 0.8673156381119043
title: 'BadAssDemocrats.com, LLC'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-60002689-7
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1aa0e0'
    - '#df0f21'
    - '#302857'
    - '#827d92'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
