name: badassdemocrats.com
favicon: null
layout_spectrum: 0.2547852660063654
typography_spectrum: 0.8673156381119043
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
