name: badassdemocrats.com
favicon: null
layout_spectrum: 0.2547852660063654
typography_spectrum: 0.8673156381119043
title: Bad Ass Democrats
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-60002689-7
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0033cc'
    - '#cc0000'
    - '#aaa5a1'
    - '#6678d4'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
